export {
  activateSpeechModel,
  cancelDictation,
  cancelSpeechModel,
  currentDictationWebview,
  deleteSpeechModel,
  finishDictation,
  getDictationOwner,
  installSpeechModel,
  listenDictationOwner,
  listenSpeechModelProgress,
  listenSpeechModelsChanged,
  listSpeechModels,
  openSpeechSystemSettings,
  prepareSpeechModel,
  setSpeechLanguage,
  startDictation,
  type DictationFailureDto,
  type DictationOwnerDto,
  type SpeechJobDto,
  type SpeechLanguageDto,
  type SpeechModelDto,
  type SpeechModelsDto,
} from "@/platform/speech/speech-api";
